Fix intermittent off-by-one error in rest-service test
QueryServiceTest.testTotalQuery computes its own start/end
values based on when it calls System.currentTimeMillis() and
QueryService.getQueryString also calls currentTimeMillis()
which will cause the expected result to be off on occasion:

    QueryServiceTest.testTotalQuery:99 expected: <start=1703196215> but was: <start=1703196216>

Add another method signature to getQueryString so we can pass
in our value of 'end' from our test to ensure the comparisions
always pass. This succeded for > 1 million runs for me, where
before it would fail around 10k - 100k runs.